// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvR6p1ue1FmSnAotJTTyIzCfDIAXgcow4',
    appId: '1:692650698261:web:35201ca5dcbb4c7ea5501c',
    messagingSenderId: '692650698261',
    projectId: 'hundyp-flutter',
    authDomain: 'hundyp-flutter.firebaseapp.com',
    storageBucket: 'hundyp-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA-7aLpRv1FQIuhmf5dE2qCvt0TDSNWIo',
    appId: '1:692650698261:android:97404ec0d74803c1a5501c',
    messagingSenderId: '692650698261',
    projectId: 'hundyp-flutter',
    storageBucket: 'hundyp-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLT_D4UuyXIxqQ1UAqqVo_LtEBHdFc2L0',
    appId: '1:692650698261:ios:12f322511817837fa5501c',
    messagingSenderId: '692650698261',
    projectId: 'hundyp-flutter',
    storageBucket: 'hundyp-flutter.firebasestorage.app',
    iosBundleId: 'com.example.hundyp',
  );
}
