name: Deploy to Firebase Hosting on Merge

on:
  push:
    branches:
#       - main
# todo need env vars on github

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
      - run: |
          git config --global --add safe.directory /opt/hostedtoolcache/flutter/stable-3.3.10-x64
          flutter build bundle

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build the Flutter web app
      - name: Build Flutter web app
        run: flutter build web

      # Step 5: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HUNDYP_FLUTTER }}
          projectId: hundyp-flutter
          channelId: live
